spring:
  sql:
    init:
      mode: always
  h2:
    console:
      enabled: true
      path: /h2

  datasource:
    url: jdbc:h2:mem:testdb;DATABASE_TO_UPPER=false
    username: sa
    password: sa
    driver-class-name: org.h2.Driver

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    defer-datasource-initialization: true

  main:
    banner-mode: off

